apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Cloudethix WebApp</title>
      <meta charset="utf-8">
    </head>
    <body>
      <h1>I am Cloudethix Team, Are you ?!!</h1>
      <p>Version: 1.1</p>
    </body>
    </html>
