apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-webapp-deployment
  labels:
    app: frontend-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-webapp
  template:
    metadata:
      labels:
        app: frontend-webapp
    spec:
      containers:
      - name: frontend-webapp-container
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: frontend-config-volume
          mountPath: /usr/share/nginx/html/
      volumes:
      - name: frontend-config-volume
        configMap:
          name: frontend-config
          items:
          - key: index.html
            path: index.html
